import { Helmet } from "react-helmet-async";
import { motion } from "framer-motion";

const TermsOfService = () => {
  return (
    <>
      <Helmet>
        <title>Terms of Service | InterviewGen AI</title>

        <meta
          name="description"
          content="Read the Terms of Service for InterviewGen AI. Learn about acceptable use, user responsibilities, intellectual property, disclaimers, and limitations of liability."
        />

        <meta name="robots" content="index, follow" />

        <link rel="canonical" href="https://your-domain.com/terms-of-service" />
      </Helmet>

      <div className="min-h-screen bg-[#030712] text-gray-300">
        <div className="max-w-5xl mx-auto px-6 py-20">
          <motion.h1
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-5xl font-bold text-white mb-4"
          >
            Terms of Service
          </motion.h1>

          <p className="text-gray-400 mb-12">Last Updated: July 13, 2026</p>

          <div className="space-y-10">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                1. Acceptance of Terms
              </h2>

              <p>
                By accessing or using InterviewGen AI, you agree to be bound by
                these Terms of Service. If you do not agree with any part of
                these terms, please discontinue use of the platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                2. Description of Service
              </h2>

              <p>
                InterviewGen AI provides AI-powered interview preparation
                features, including resume analysis, job description matching,
                interview questions, skill gap analysis, and personalized
                preparation reports.
              </p>

              <p className="mt-3">
                The platform is currently offered free of charge. We reserve the
                right to introduce, modify, or discontinue features at any time.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                3. User Responsibilities
              </h2>

              <ul className="list-disc pl-6 space-y-2">
                <li>Provide accurate information.</li>
                <li>Keep your account credentials secure.</li>
                <li>Do not misuse or attempt to disrupt the platform.</li>
                <li>
                  Do not upload illegal, harmful, or copyrighted content without
                  permission.
                </li>
                <li>
                  Comply with all applicable laws while using the service.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                4. AI-Generated Content
              </h2>

              <p>
                Reports and recommendations generated by AI are intended for
                educational and interview preparation purposes only. They should
                not be considered professional employment, legal, or career
                advice.
              </p>

              <p className="mt-3">
                While we strive to provide accurate results, InterviewGen AI
                does not guarantee the completeness, accuracy, or suitability of
                AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                5. Intellectual Property
              </h2>

              <p>
                All website content, branding, logos, design, software, and
                features are owned by InterviewGen AI unless otherwise stated.
                You may not copy, reproduce, distribute, or modify any part of
                the platform without prior written permission.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                6. Account Termination
              </h2>

              <p>
                We reserve the right to suspend or terminate accounts that
                violate these Terms of Service or engage in fraudulent, abusive,
                or harmful activities.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                7. Limitation of Liability
              </h2>

              <p>
                InterviewGen AI shall not be liable for any direct, indirect,
                incidental, or consequential damages resulting from your use of
                the platform or reliance on AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                8. Third-Party Services
              </h2>

              <p>
                Our platform may integrate with third-party AI providers,
                authentication services, analytics tools, or other external
                services. Their use is governed by their respective terms and
                privacy policies.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                9. Privacy
              </h2>

              <p>
                Your use of InterviewGen AI is also governed by our Privacy
                Policy, which explains how we collect, store, and use your
                information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                10. Changes to These Terms
              </h2>

              <p>
                We may revise these Terms of Service from time to time. Updated
                versions will be posted on this page with the latest revision
                date. Continued use of the platform constitutes acceptance of
                the revised terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                11. Governing Law
              </h2>

              <p>
                These Terms of Service shall be governed by and interpreted in
                accordance with the applicable laws of India.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-3">
                12. Contact Us
              </h2>

              <p>
                If you have any questions regarding these Terms of Service,
                please contact us through the help center available on the
                website.
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsOfService;
